package com.hello.order.mapper;

import com.hello.order.model.ChannelOrder;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ChannelOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_order
     *
     * @mbg.generated
     */
    int insert(ChannelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_order
     *
     * @mbg.generated
     */
    ChannelOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_order
     *
     * @mbg.generated
     */
    List<ChannelOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChannelOrder record);
}