package com.hello.order.model;

public class ChannelOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_order.order_code
     *
     * @mbg.generated
     */
    private String orderCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_order.source_content
     *
     * @mbg.generated
     */
    private String sourceContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_order.id
     *
     * @return the value of channel_order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_order.id
     *
     * @param id the value for channel_order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_order.order_code
     *
     * @return the value of channel_order.order_code
     *
     * @mbg.generated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_order.order_code
     *
     * @param orderCode the value for channel_order.order_code
     *
     * @mbg.generated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_order.source_content
     *
     * @return the value of channel_order.source_content
     *
     * @mbg.generated
     */
    public String getSourceContent() {
        return sourceContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_order.source_content
     *
     * @param sourceContent the value for channel_order.source_content
     *
     * @mbg.generated
     */
    public void setSourceContent(String sourceContent) {
        this.sourceContent = sourceContent == null ? null : sourceContent.trim();
    }
}