package com.hello.mapper;

import com.hello.model.FarmFarmer;
import java.util.List;

public interface FarmFarmerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm_farmer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm_farmer
     *
     * @mbg.generated
     */
    int insert(FarmFarmer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm_farmer
     *
     * @mbg.generated
     */
    FarmFarmer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm_farmer
     *
     * @mbg.generated
     */
    List<FarmFarmer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm_farmer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FarmFarmer record);
}