package com.hello.mapper;

import com.hello.model.Farm;
import java.util.List;

public interface FarmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbg.generated
     */
    int insert(Farm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbg.generated
     */
    Farm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbg.generated
     */
    List<Farm> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Farm record);
}