package com.hello.mapper;

import com.hello.model.FarmDesc;
import java.util.List;

public interface FarmDescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm_desc
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm_desc
     *
     * @mbg.generated
     */
    int insert(FarmDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm_desc
     *
     * @mbg.generated
     */
    FarmDesc selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm_desc
     *
     * @mbg.generated
     */
    List<FarmDesc> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm_desc
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FarmDesc record);
}