package com.hello.model;

public class FarmFarmer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm_farmer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm_farmer.farm_id
     *
     * @mbg.generated
     */
    private Long farmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm_farmer.farmer_id
     *
     * @mbg.generated
     */
    private Long farmerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm_farmer.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm_farmer.id
     *
     * @return the value of farm_farmer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm_farmer.id
     *
     * @param id the value for farm_farmer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm_farmer.farm_id
     *
     * @return the value of farm_farmer.farm_id
     *
     * @mbg.generated
     */
    public Long getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm_farmer.farm_id
     *
     * @param farmId the value for farm_farmer.farm_id
     *
     * @mbg.generated
     */
    public void setFarmId(Long farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm_farmer.farmer_id
     *
     * @return the value of farm_farmer.farmer_id
     *
     * @mbg.generated
     */
    public Long getFarmerId() {
        return farmerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm_farmer.farmer_id
     *
     * @param farmerId the value for farm_farmer.farmer_id
     *
     * @mbg.generated
     */
    public void setFarmerId(Long farmerId) {
        this.farmerId = farmerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm_farmer.description
     *
     * @return the value of farm_farmer.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm_farmer.description
     *
     * @param description the value for farm_farmer.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}