package com.hello.model;

public class Point {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.region_id
     *
     * @mbg.generated
     */
    private Long regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.lat
     *
     * @mbg.generated
     */
    private Double lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.lng
     *
     * @mbg.generated
     */
    private Double lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.position
     *
     * @mbg.generated
     */
    private Short position;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.id
     *
     * @return the value of point.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.id
     *
     * @param id the value for point.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.region_id
     *
     * @return the value of point.region_id
     *
     * @mbg.generated
     */
    public Long getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.region_id
     *
     * @param regionId the value for point.region_id
     *
     * @mbg.generated
     */
    public void setRegionId(Long regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.lat
     *
     * @return the value of point.lat
     *
     * @mbg.generated
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.lat
     *
     * @param lat the value for point.lat
     *
     * @mbg.generated
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.lng
     *
     * @return the value of point.lng
     *
     * @mbg.generated
     */
    public Double getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.lng
     *
     * @param lng the value for point.lng
     *
     * @mbg.generated
     */
    public void setLng(Double lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.position
     *
     * @return the value of point.position
     *
     * @mbg.generated
     */
    public Short getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.position
     *
     * @param position the value for point.position
     *
     * @mbg.generated
     */
    public void setPosition(Short position) {
        this.position = position;
    }
}